server:
  port: 80

spring:
  application:
    name: mt-music

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driverClassName: com.mysql.cj.jdbc.Driver               # mysql驱动包
    url: jdbc:mysql://localhost:3306/study?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: caoyangcan


